# Generated by Django 4.2.4 on 2024-01-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_trangthai_delete_choice_khachhang_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='trang_thai',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.trangthai'),
        ),
    ]
