# Generated by Django 4.2.4 on 2023-10-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_employee_service_khachhang_employee_assigned_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='ticket_number',
            field=models.IntegerField(null=True),
        ),
    ]
