# Generated by Django 4.2.4 on 2023-10-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_khachhang_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='is_calling',
            field=models.BooleanField(default=False),
        ),
    ]
