# Generated by Django 3.2.2 on 2024-01-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_thongke_ngay_quet'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='ngay_sinh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='so_cccd',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
