# Generated by Django 4.2.4 on 2023-10-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_khachhang_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='feedback',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
