# Generated by Django 3.2.2 on 2024-01-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20240124_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongke',
            name='ngay_sinh',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='thongke',
            name='so_cccd',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
