# Generated by Django 4.2.10 on 2024-03-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20240124_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapNhatDuLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('thong_bao', models.TextField()),
            ],
        ),
    ]
