# Generated by Django 4.2.10 on 2024-03-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_capnhatdulieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='capnhatdulieu',
            name='tong',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='capnhatdulieu',
            name='thong_bao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
