# Generated by Django 4.2.10 on 2024-03-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_danhsachcho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='trang_thai',
            field=models.BooleanField(default=True),
        ),
    ]
