# Generated by Django 4.2.10 on 2024-03-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_danhsachcho_name_danhsachcho_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhsachcho',
            name='employee',
            field=models.IntegerField(null=True),
        ),
    ]
