# Generated by Django 4.2.1 on 2023-05-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donkethon',
            old_name='file',
            new_name='vitri_file',
        ),
    ]
