# Generated by Django 4.2.4 on 2023-10-13 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonChungNhanHonNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_va_ten_nguoi_yeu_cau', models.TextField(max_length=100)),
                ('so_cccd_nguoi_yeu_cau', models.CharField(max_length=20)),
                ('ho_va_ten', models.TextField(max_length=100)),
                ('so_cccd', models.CharField(max_length=20)),
                ('ngay_lam_don', models.DateTimeField(default=django.utils.timezone.now)),
                ('thanh_tien', models.CharField(max_length=20)),
                ('ghi_chu', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=254, upload_to='QRcodes/reports/HonNhan')),
            ],
        ),
        migrations.CreateModel(
            name='Donkethon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_va_ten_nam', models.TextField(max_length=100)),
                ('so_cccd_nam', models.CharField(max_length=20)),
                ('ho_va_ten_nu', models.TextField(max_length=100)),
                ('so_cccd_nu', models.CharField(max_length=20)),
                ('ngay_lam_don', models.DateTimeField(default=django.utils.timezone.now)),
                ('thanh_tien', models.CharField(max_length=20)),
                ('ghi_chu', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=254, upload_to='QRcodes/reports/kethon')),
            ],
        ),
        migrations.CreateModel(
            name='DonKhaiSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_va_ten_nguoi_yeu_cau', models.TextField(max_length=100)),
                ('so_cccd', models.CharField(max_length=20)),
                ('ho_va_ten_khai_sinh', models.TextField(max_length=100)),
                ('gioi_tinh', models.TextField(max_length=10)),
                ('nam_sinh_khai_sinh', models.CharField(max_length=50)),
                ('ho_va_ten_cha', models.TextField(max_length=100)),
                ('nam_sinh_cha', models.CharField(max_length=20)),
                ('ho_va_ten_me', models.TextField(max_length=100)),
                ('nam_sinh_me', models.CharField(max_length=20)),
                ('ngay_lam_don', models.DateTimeField(default=django.utils.timezone.now)),
                ('thanh_tien', models.CharField(max_length=20)),
                ('ghi_chu', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=254, upload_to='QRcodes/reports/kethon')),
            ],
        ),
        migrations.CreateModel(
            name='Donkhaitu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_va_ten', models.TextField(max_length=100)),
                ('so_cccd', models.CharField(max_length=20)),
                ('ho_va_ten_nguoi_mat', models.TextField(max_length=100)),
                ('so_cccd_nguoi_mat', models.CharField(max_length=20)),
                ('ngay_lam_don', models.DateTimeField(default=django.utils.timezone.now)),
                ('thanh_tien', models.CharField(max_length=20)),
                ('ghi_chu', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=254, upload_to='QRcodes/reports/khai_tu')),
            ],
        ),
        migrations.CreateModel(
            name='DonTrichLucHoTich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_va_ten_nguoi_yeu_cau', models.TextField(max_length=100)),
                ('so_cccd_nguoi_yeu_cau', models.CharField(max_length=20)),
                ('loai_don', models.CharField(max_length=1001)),
                ('ho_va_ten_nguoi_lam_ho', models.TextField(max_length=100)),
                ('so_cccd', models.CharField(max_length=20)),
                ('ngay_lam_don', models.DateTimeField(default=django.utils.timezone.now)),
                ('thanh_tien', models.CharField(max_length=20)),
                ('ghi_chu', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=254, upload_to='QRcodes/reports/HoTich')),
            ],
        ),
        migrations.CreateModel(
            name='Loaidon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_don', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThongtinQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_cccd', models.CharField(max_length=20)),
                ('so_cmnd_cu', models.CharField(max_length=20)),
                ('ho_va_ten', models.TextField(max_length=100)),
                ('ngay_sinh', models.CharField(max_length=20)),
                ('gioi_tinh', models.CharField(max_length=10)),
                ('dia_chi', models.TextField(max_length=2000)),
                ('ngay_cap', models.TextField(max_length=150)),
                ('ngay_quet', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
