# Generated by Django 4.2.4 on 2023-10-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0002_donchungnhanhonnhan_donkethon_donkhaisinh_donkhaitu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThongtinQR',
        ),
    ]
