# Generated by Django 4.1.5 on 2023-05-06 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0002_thongtinqr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donkethon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_va_ten_nam', models.TextField(max_length=100)),
                ('so_cccd_nam', models.CharField(max_length=20)),
                ('ngay_sinh_nam', models.CharField(max_length=20)),
                ('ho_va_ten_nu', models.TextField(max_length=100)),
                ('so_cccd_nu', models.CharField(max_length=20)),
                ('ngay_sinh_nu', models.CharField(max_length=20)),
                ('ngay_lam_don', models.DateTimeField(default=django.utils.timezone.now)),
                ('ghi_chu', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=254, upload_to='QRcodes/reports/kethon')),
            ],
        ),
        migrations.CreateModel(
            name='Loaidon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_don', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
