# Generated by Django 3.2.2 on 2024-01-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0003_delete_thongtinqr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonChungNhanHonNhan',
        ),
        migrations.DeleteModel(
            name='Donkethon',
        ),
        migrations.DeleteModel(
            name='DonKhaiSinh',
        ),
        migrations.DeleteModel(
            name='Donkhaitu',
        ),
        migrations.DeleteModel(
            name='DonTrichLucHoTich',
        ),
        migrations.DeleteModel(
            name='Loaidon',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
