# Generated by Django 4.1.5 on 2023-05-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0004_donchungnhanhonnhan_dontrichluchotich'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dontrichluchotich',
            old_name='ho_va_ten_nu',
            new_name='ho_va_ten_nguoi_lam_ho',
        ),
        migrations.RenameField(
            model_name='dontrichluchotich',
            old_name='ngay_sinh_nu',
            new_name='so_cccd',
        ),
        migrations.RemoveField(
            model_name='dontrichluchotich',
            name='so_cccd_nu',
        ),
    ]
