# Generated by Django 4.1.5 on 2023-06-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0005_rename_ho_va_ten_nu_dontrichluchotich_ho_va_ten_nguoi_lam_ho_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donkethon',
            old_name='ngay_sinh_nam',
            new_name='thanh_tien',
        ),
        migrations.RemoveField(
            model_name='donkethon',
            name='ngay_sinh_nu',
        ),
    ]
