# Generated by Django 4.1.5 on 2023-06-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0007_donkhaitu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dontrichluchotich',
            old_name='ngay_sinh',
            new_name='thanh_tien',
        ),
        migrations.AddField(
            model_name='dontrichluchotich',
            name='loai_don',
            field=models.CharField(default=1, max_length=1001),
            preserve_default=False,
        ),
    ]
