# Generated by Django 4.1.5 on 2023-06-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0008_rename_ngay_sinh_dontrichluchotich_thanh_tien_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donchungnhanhonnhan',
            old_name='ngay_sinh',
            new_name='thanh_tien',
        ),
        migrations.RemoveField(
            model_name='donchungnhanhonnhan',
            name='ngay_sinh_nu',
        ),
        migrations.AlterField(
            model_name='donchungnhanhonnhan',
            name='file',
            field=models.FileField(max_length=254, upload_to='QRcodes/reports/HonNhan'),
        ),
        migrations.AlterField(
            model_name='dontrichluchotich',
            name='file',
            field=models.FileField(max_length=254, upload_to='QRcodes/reports/HoTich'),
        ),
    ]
