# Generated by Django 4.1.5 on 2023-07-12 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0010_rename_ho_va_ten_nu_donchungnhanhonnhan_ho_va_ten_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonKhaiSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_va_ten_nguoi_yeu_cau', models.TextField(max_length=100)),
                ('so_cccd', models.CharField(max_length=20)),
                ('ho_va_ten_khai_sinh', models.TextField(max_length=100)),
                ('gioi_tinh', models.TextField(max_length=10)),
                ('nam_sinh_khai_sinh', models.CharField(max_length=50)),
                ('ho_va_ten_cha', models.TextField(max_length=100)),
                ('nam_sinh_cha', models.CharField(max_length=20)),
                ('ho_va_ten_me', models.TextField(max_length=100)),
                ('nam_sinh_me', models.CharField(max_length=20)),
                ('ngay_lam_don', models.DateTimeField(default=django.utils.timezone.now)),
                ('thanh_tien', models.CharField(max_length=20)),
                ('ghi_chu', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=254, upload_to='QRcodes/reports/kethon')),
            ],
        ),
    ]
