# Generated by Django 4.2.4 on 2023-10-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0004_donkhaisinh'),
        ('QRcodes', '0011_donkhaisinh'),
    ]

    operations = [
    ]
