# Generated by Django 4.2.4 on 2024-01-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('expiration_date', models.DateField()),
                ('max_users', models.PositiveIntegerField()),
                ('used_users', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
